// GENERATED by scripts/solve-challenges.ts – do not edit by hand.
import type { LevelTuning } from '../../game/challenge';

/** Seed per stage and star thresholds of every level. */
export const TUNING: Readonly<Record<string, LevelTuning>> = {
  'w1-01': {
    seeds: [101000],
    stars: [
      { kind: 'time', seconds: 102 },
      { kind: 'bombs', max: 26 },
    ],
  },
  'w1-02': {
    seeds: [102007],
    stars: [
      { kind: 'time', seconds: 85 },
      { kind: 'bombs', max: 30 },
    ],
  },
  'w1-03': {
    seeds: [103000],
    stars: [
      { kind: 'time', seconds: 30 },
      { kind: 'bombs', max: 6 },
    ],
  },
  'w1-04': {
    seeds: [104002],
    stars: [
      { kind: 'time', seconds: 55 },
      { kind: 'bombs', max: 9 },
    ],
  },
  'w1-05': {
    seeds: [105000],
    stars: [
      { kind: 'time', seconds: 63 },
      { kind: 'bombs', max: 15 },
    ],
  },
  'w1-06': {
    seeds: [106000],
    stars: [
      { kind: 'bombs', max: 20 },
      { kind: 'pickups', min: 1 },
    ],
  },
  'w1-07': {
    seeds: [107000],
    stars: [
      { kind: 'time', seconds: 85 },
      { kind: 'bombs', max: 22 },
    ],
  },
  'w1-08': {
    seeds: [108001],
    stars: [
      { kind: 'time', seconds: 80 },
      { kind: 'bombs', max: 15 },
    ],
  },
  'w1-09': { seeds: [109005], stars: [{ kind: 'time', seconds: 60 }, { kind: 'noDamage' }] },
  'w1-10': {
    seeds: [110000],
    stars: [
      { kind: 'time', seconds: 30 },
      { kind: 'bombs', max: 6 },
    ],
  },
  'w1-11': {
    seeds: [111000],
    stars: [
      { kind: 'time', seconds: 60 },
      { kind: 'bombs', max: 13 },
    ],
  },
  'w1-12': {
    seeds: [112001, 112103, 112200],
    stars: [
      { kind: 'time', seconds: 315 },
      { kind: 'bombs', max: 56 },
    ],
  },
  'w2-01': {
    seeds: [201000],
    stars: [
      { kind: 'time', seconds: 102 },
      { kind: 'bombs', max: 32 },
    ],
  },
  'w2-02': {
    seeds: [202000],
    stars: [
      { kind: 'time', seconds: 55 },
      { kind: 'bombs', max: 13 },
    ],
  },
  'w2-03': {
    seeds: [203000],
    stars: [
      { kind: 'time', seconds: 40 },
      { kind: 'bombs', max: 8 },
    ],
  },
  'w2-04': {
    seeds: [204000],
    stars: [
      { kind: 'time', seconds: 85 },
      { kind: 'bombs', max: 18 },
    ],
  },
  'w2-05': { seeds: [205000], stars: [{ kind: 'time', seconds: 35 }, { kind: 'noDamage' }] },
  'w2-06': {
    seeds: [206000],
    stars: [
      { kind: 'bombs', max: 25 },
      { kind: 'pickups', min: 1 },
    ],
  },
  'w2-07': {
    seeds: [207000],
    stars: [
      { kind: 'time', seconds: 102 },
      { kind: 'bombs', max: 25 },
    ],
  },
  'w2-08': {
    seeds: [208002],
    stars: [
      { kind: 'time', seconds: 165 },
      { kind: 'bombs', max: 25 },
    ],
  },
  'w2-09': { seeds: [209001], stars: [{ kind: 'time', seconds: 20 }, { kind: 'noDamage' }] },
  'w2-10': {
    seeds: [210001],
    stars: [
      { kind: 'time', seconds: 90 },
      { kind: 'bombs', max: 15 },
    ],
  },
  'w2-11': {
    seeds: [211002],
    stars: [
      { kind: 'time', seconds: 95 },
      { kind: 'bombs', max: 14 },
    ],
  },
  'w2-12': {
    seeds: [212000, 212100, 212200],
    stars: [
      { kind: 'time', seconds: 360 },
      { kind: 'bombs', max: 47 },
    ],
  },
  'w3-01': {
    seeds: [301000],
    stars: [
      { kind: 'time', seconds: 119 },
      { kind: 'bombs', max: 32 },
    ],
  },
  'w3-02': {
    seeds: [302001],
    stars: [
      { kind: 'time', seconds: 16 },
      { kind: 'bombs', max: 4 },
    ],
  },
  'w3-03': {
    seeds: [303001],
    stars: [
      { kind: 'time', seconds: 35 },
      { kind: 'bombs', max: 8 },
    ],
  },
  'w3-04': {
    seeds: [304000],
    stars: [
      { kind: 'time', seconds: 40 },
      { kind: 'bombs', max: 8 },
    ],
  },
  'w3-05': {
    seeds: [305001],
    stars: [
      { kind: 'time', seconds: 110 },
      { kind: 'bombs', max: 18 },
    ],
  },
  'w3-06': {
    seeds: [306000],
    stars: [
      { kind: 'bombs', max: 29 },
      { kind: 'pickups', min: 1 },
    ],
  },
  'w3-07': {
    seeds: [307000],
    stars: [
      { kind: 'time', seconds: 155 },
      { kind: 'bombs', max: 13 },
    ],
  },
  'w3-08': { seeds: [308001], stars: [{ kind: 'time', seconds: 68 }, { kind: 'noDamage' }] },
  'w3-09': {
    seeds: [309000],
    stars: [
      { kind: 'time', seconds: 119 },
      { kind: 'bombs', max: 35 },
    ],
  },
  'w3-10': {
    seeds: [310004],
    stars: [
      { kind: 'bombs', max: 20 },
      { kind: 'pickups', min: 3 },
    ],
  },
  'w3-11': {
    seeds: [311005],
    stars: [
      { kind: 'time', seconds: 110 },
      { kind: 'bombs', max: 17 },
    ],
  },
  'w3-12': {
    seeds: [312002, 312101, 312202],
    stars: [
      { kind: 'time', seconds: 265 },
      { kind: 'bombs', max: 45 },
    ],
  },
};
