/**
 * The tutorial (T5.4, PLAN §1.11): five short interactive steps with the real controls, played
 * through the challenge machinery as one five-stage level –
 *
 * 1. move: reach the flag,
 * 2. place a pop and hide: blast the few crates,
 * 3. blast crates and pick up power-ups,
 * 4. a chain reaction: one pop sets off another,
 * 5. beat an Easy bot.
 *
 * Like every built-in challenge it has seeds and a reference solution generated by
 * `scripts/solve-challenges.ts` (key `tutorial`) that `npm run check` replays. The bot never sets
 * off a chain on purpose, so the solver opens step 4 with {@link chainOpening}.
 */

import { BotLevel, Dir, encodeInput } from '../core';
import type { LevelDef } from '../game/challenge';
import { ARENA_CROSSROADS, ARENA_GARDEN } from './arenas';
import { variant } from './challenges/arenas';

export const TUTORIAL_ID = 'tutorial';
export const TUTORIAL_STEPS = 5;

export const TUTORIAL: LevelDef = {
  id: TUTORIAL_ID,
  world: 0,
  index: 0,
  nameKey: 'tutorialTitle',
  stars: ['time', 'bombs'],
  stages: [
    {
      arena: variant(ARENA_GARDEN, 'tut-walk', 0),
      flag: { x: 11, y: 11 },
      objective: { type: 'flag', seconds: 60 },
    },
    {
      arena: variant(ARENA_GARDEN, 'tut-pop', 8),
      rules: { powerupChance: 0 },
      objective: { type: 'crates', seconds: 90 },
    },
    {
      arena: variant(ARENA_GARDEN, 'tut-loot', 20),
      rules: { powerupChance: 100 },
      objective: { type: 'collect', count: 2, seconds: 90 },
    },
    {
      arena: variant(ARENA_GARDEN, 'tut-chain', 0),
      rules: { startBombs: 3, powerupChance: 0 },
      objective: { type: 'chain', count: 1, seconds: 90 },
    },
    {
      arena: variant(ARENA_CROSSROADS, 'tut-duel', 50),
      bots: [BotLevel.EASY],
      rules: { roundSeconds: 75, suddenDeath: 'spiral' },
      objective: { type: 'win' },
    },
  ],
};

/**
 * Reference opening of the chain step (the solver plays it before the bot takes over): after the
 * countdown, pop, step right, pop again (the second pop sits in the first one's flame), step right
 * and down out of both crosses, wait for the blasts.
 */
export function chainOpening(): number[] {
  const bytes: number[] = [];
  const add = (v: number, n: number): void => {
    for (let i = 0; i < n; i++) bytes.push(v);
  };
  const pop = encodeInput(Dir.NONE, Dir.NONE, true);
  add(0, 182);
  add(pop, 1);
  add(encodeInput(Dir.RIGHT), 16);
  add(pop, 1);
  add(encodeInput(Dir.RIGHT), 16);
  add(encodeInput(Dir.DOWN), 16);
  add(0, 200);
  return bytes;
}
