/** Public API of the deterministic simulation core. Outer layers import from here only. */

export { SIM_VERSION } from './version';
export { FNV_OFFSET, fnv1aBytes, fnv1aU32, hashBytes, hashHex } from './hash';
export {
  RNG_STREAM_COUNT,
  RNG_WORDS,
  RngStream,
  createRngWords,
  nextU32,
  randInt,
  randPercent,
  randWeighted,
  seedAllStreams,
  seedStream,
  type RngStreamId,
} from './rng';
export {
  Ability,
  BombFlag,
  CELL_COUNT,
  GRID_H,
  GRID_W,
  HALF_TILE,
  Hdr,
  JINX_EFFECT_COUNT,
  Jinx,
  MAX_BOMBS,
  NO_GOAL,
  MAX_SEATS,
  NO_OWNER,
  NO_SIDE,
  PICKUP_KIND_COUNT,
  Phase,
  Pickup,
  RuleFlag,
  STATE_BYTES,
  TILE,
  Tile,
  cellIndex,
  cloneState,
  createEmptyState,
  inBounds,
  isSeatActive,
  playerCell,
  restore,
  sideOf,
  snapshot,
  snapshotInto,
  stateHash,
  tileCenter,
  toTile,
  type PickupKind,
  type SimState,
  type TileType,
} from './state';
export {
  DIR_DX,
  DIR_DY,
  Dir,
  INPUT_BOMB,
  NO_INPUT,
  encodeInput,
  inputBomb,
  inputMain,
  inputSecondary,
  packInputs,
  unpackInputs,
  type Direction,
} from './input';
export {
  ARENA_SIZE,
  DEFAULT_CRATE_DENSITY,
  DEFAULT_POWERUP_CHANCE,
  DEFAULT_POWERUP_WEIGHTS,
  LayoutCell,
  fillArena,
  loadArena,
  parseArena,
  spawnSafeL,
  validateArena,
  type ArenaDef,
  type ArenaError,
  type ArenaErrorCode,
  type ArenaValidation,
  type LayoutCellType,
  type ParsedArena,
} from './arena';
export {
  BOMB_BUFFER_TICKS,
  CHAIN_DELAY,
  FLAME_TICKS,
  FUSE_TICKS,
  PICKUP_GRACE,
  addBomb,
  bombAt,
  bombCount,
  bombsInUse,
  bombsOwnedBy,
  KICK_SPEED,
  TOSS_DISTANCE,
  bombCanEnter,
  canPassBomb,
  kickBomb,
  removeBomb,
  slideBombs,
} from './bombs';
export { EventKind, type EventKindId, type SimEvent } from './events';
export {
  HASTE_INTERVAL,
  JINX_TICKS,
  JINX_TOUCH,
  JINX_TRANSFER_COOLDOWN,
  MAX_BOMB_CAPACITY,
  MAX_DROPS,
  MAX_RANGE,
  SHIELD_INVULN,
  applyPickup,
  dropPickups,
  jinxInput,
} from './powerups';
export {
  BASE_SPEED,
  CORNER_ASSIST,
  MAX_SPEED_LEVEL,
  ROLLER_SPEED,
  isPassable,
  movePlayer,
  playerSpeed,
} from './movement';
export {
  CHAOS_RULES,
  CLASSIC_RULES,
  DEFAULT_RULES,
  FAST_RULES,
  RULE_PRESETS,
  WINS_TO_MATCH_OPTIONS,
  type CoreRules,
  type PresetId,
  type Rules,
} from './rules';
export { chooseSpawns, createState, type MatchSetup } from './setup';
export {
  COUNTDOWN_TICKS,
  GHOST_BOMB_COOLDOWN,
  GHOST_BOMB_FUSE,
  GHOST_BOMB_RANGE,
  ROUND_END_TICKS,
  SD_INTERVAL,
  SD_PAUSE_AT,
  SD_PAUSE_TICKS,
  SPIRAL,
} from './round';
export { isMatchOver } from './match';
export { currentTick, step } from './step';
export {
  ReplayRecorder,
  appendInputs,
  forEachTick,
  rleDecode,
  rleEncode,
  rleLength,
  runReplay,
  type InputRLE,
  type Replay,
  type ReplayResult,
} from './replay';
export { botInput } from './ai/bot';
export {
  BotLevel,
  botLevel,
  botProfile,
  hasBots,
  setBotLevel,
  type BotLevelId,
  type BotProfile,
} from './ai/difficulty';
export { SAFE as DANGER_SAFE, computeDanger, dEnd, dStart } from './ai/danger';
