/** Public API of the deterministic simulation core. Outer layers import from here only. */

export { SIM_VERSION } from './version';
export { FNV_OFFSET, fnv1aBytes, fnv1aU32, hashBytes, hashHex } from './hash';
export {
  RNG_STREAM_COUNT,
  RNG_WORDS,
  RngStream,
  createRngWords,
  nextU32,
  randInt,
  randPercent,
  randWeighted,
  seedAllStreams,
  seedStream,
  type RngStreamId,
} from './rng';
export {
  Ability,
  CELL_COUNT,
  GRID_H,
  GRID_W,
  HALF_TILE,
  Hdr,
  MAX_BOMBS,
  MAX_SEATS,
  NO_OWNER,
  PICKUP_KIND_COUNT,
  Phase,
  Pickup,
  STATE_BYTES,
  TILE,
  Tile,
  cellIndex,
  cloneState,
  createEmptyState,
  inBounds,
  isSeatActive,
  playerCell,
  restore,
  snapshot,
  snapshotInto,
  stateHash,
  tileCenter,
  toTile,
  type PickupKind,
  type SimState,
  type TileType,
} from './state';
export {
  DIR_DX,
  DIR_DY,
  Dir,
  INPUT_BOMB,
  NO_INPUT,
  encodeInput,
  inputBomb,
  inputMain,
  inputSecondary,
  packInputs,
  unpackInputs,
  type Direction,
} from './input';
export {
  ARENA_SIZE,
  DEFAULT_CRATE_DENSITY,
  DEFAULT_POWERUP_CHANCE,
  DEFAULT_POWERUP_WEIGHTS,
  LayoutCell,
  fillArena,
  loadArena,
  parseArena,
  spawnSafeL,
  validateArena,
  type ArenaDef,
  type ArenaError,
  type ArenaErrorCode,
  type ArenaValidation,
  type LayoutCellType,
  type ParsedArena,
} from './arena';
export { addBomb, bombAt, bombCount, bombsOwnedBy, canPassBomb, removeBomb } from './bombs';
export {
  BASE_SPEED,
  CORNER_ASSIST,
  MAX_SPEED_LEVEL,
  ROLLER_SPEED,
  isPassable,
  movePlayer,
  playerSpeed,
} from './movement';
export {
  DEFAULT_RULES,
  MAX_BOMB_CAPACITY,
  MAX_RANGE,
  createState,
  type CoreRules,
  type MatchSetup,
} from './setup';
export { currentTick, step, type SimEvent } from './step';
