// Generates every app icon and launch-screen image from the code-drawn brand art (T7.2):
//   npm run assets            (node scripts/run-ts.mjs scripts/assets.ts)
// Renders the SVGs of scripts/brand.ts in headless Chromium (Playwright, already a dev
// dependency) and writes the Android mipmaps / splash drawables, the iOS asset catalog and the
// web favicon. The outputs are committed; `tests/unit/assets.test.ts` checks they are complete.

import { existsSync, mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { chromium, type Page } from '@playwright/test';
import {
  ADAPTIVE_BACKGROUND,
  ANDROID_DENSITIES,
  ANDROID_SPLASH,
  IOS_SPLASH,
  SPLASH_BACKGROUND,
  iconSvg,
  splashSvg,
  type IconShape,
} from './brand';

const RES = 'android/app/src/main/res';
const XCASSETS = 'ios/App/App/Assets.xcassets';

async function render(
  page: Page,
  svg: string,
  w: number,
  h: number,
  transparent: boolean,
): Promise<Buffer> {
  await page.setViewportSize({ width: w, height: h });
  await page.setContent(
    `<!doctype html><html><body style="margin:0;background:transparent">${svg}</body></html>`,
  );
  return page.screenshot({
    clip: { x: 0, y: 0, width: w, height: h },
    omitBackground: transparent,
  });
}

function write(path: string, data: Buffer | string): void {
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, data);
}

export async function main(): Promise<number> {
  // Like playwright.config.ts: fall back to the preinstalled Chromium of the dev container.
  const fallback = join(process.env.PLAYWRIGHT_BROWSERS_PATH ?? '/opt/pw-browsers', 'chromium');
  const browser = await chromium.launch(
    existsSync(chromium.executablePath()) || !existsSync(fallback)
      ? {}
      : { executablePath: fallback },
  );
  const page = await browser.newPage({ deviceScaleFactor: 1 });
  const icon = (size: number, shape: IconShape) =>
    render(page, iconSvg(size, shape), size, size, shape !== 'square');
  let files = 0;

  for (const d of ANDROID_DENSITIES) {
    write(`${RES}/mipmap-${d.dpi}/ic_launcher.png`, await icon(d.icon, 'rounded'));
    write(`${RES}/mipmap-${d.dpi}/ic_launcher_round.png`, await icon(d.icon, 'circle'));
    write(`${RES}/mipmap-${d.dpi}/ic_launcher_foreground.png`, await icon(d.layer, 'foreground'));
    files += 3;
  }
  write(
    `${RES}/values/ic_launcher_background.xml`,
    `<?xml version="1.0" encoding="utf-8"?>\n<!-- GENERATED by scripts/assets.ts -->\n<resources>\n    <color name="ic_launcher_background">${ADAPTIVE_BACKGROUND}</color>\n</resources>\n`,
  );
  for (const s of ANDROID_SPLASH) {
    write(
      `${RES}/drawable-land-${s.dpi}/splash.png`,
      await render(page, splashSvg(s.w, s.h), s.w, s.h, false),
    );
    write(
      `${RES}/drawable-port-${s.dpi}/splash.png`,
      await render(page, splashSvg(s.h, s.w), s.h, s.w, false),
    );
    files += 2;
  }
  write(`${RES}/drawable/splash.png`, await render(page, splashSvg(480, 320), 480, 320, false));
  files++;

  // iOS: one 1024 px icon without transparency (the system rounds it), the 2732 px splash.
  write(`${XCASSETS}/AppIcon.appiconset/AppIcon-512@2x.png`, await icon(1024, 'square'));
  const splash = await render(page, splashSvg(2732, 2732), 2732, 2732, false);
  for (const name of IOS_SPLASH) write(`${XCASSETS}/Splash.imageset/${name}`, splash);
  files += 1 + IOS_SPLASH.length;

  // Web: favicon and home-screen icon.
  write('public/favicon.png', await icon(64, 'circle'));
  write('public/apple-touch-icon.png', await icon(180, 'square'));
  files += 2;

  await browser.close();
  console.log(`assets: ${files} images written (splash background ${SPLASH_BACKGROUND})`);
  return 0;
}
