// Native configuration generated from the single sources of truth (T7.1, T9.5): the bundle id
// from capacitor.config.ts and the app version from package.json go to the iOS build settings
// (ios/app-id.xcconfig, included by the debug / release xcconfigs → PRODUCT_BUNDLE_IDENTIFIER,
// MARKETING_VERSION; the build number CURRENT_PROJECT_VERSION comes from the env VERSION_CODE,
// CI's run number, else 1). Android reads the bundle id from the config that `npx cap sync` copies
// into the app assets and the version from package.json (android/app/build.gradle). Runs automatically after every `npx cap sync`
// (package.json `capacitor:sync:after`).
//   node scripts/run-ts.mjs scripts/native-config.ts

import { readFileSync, writeFileSync } from 'node:fs';
import config from '../capacitor.config';

export function main(): number {
  const appId = config.appId;
  if (!appId || !/^[a-z][a-z0-9]*(\.[a-z][a-z0-9]*)+$/.test(appId)) {
    console.error(`native-config: invalid appId "${appId}" in capacitor.config.ts`);
    return 1;
  }
  const version = (JSON.parse(readFileSync('package.json', 'utf8')) as { version: string }).version;
  if (!/^\d+\.\d+\.\d+$/.test(version)) {
    console.error(`native-config: package.json version "${version}" is not x.y.z`);
    return 1;
  }
  const build = /^\d+$/.test(process.env.VERSION_CODE ?? '') ? process.env.VERSION_CODE : '1';
  writeFileSync('ios/app-id.xcconfig', xcconfig(appId, version, build ?? '1'));
  console.log(`native-config: ${appId} ${version} (${build}) → ios/app-id.xcconfig`);
  return 0;
}

/** The generated iOS settings. */
export function xcconfig(appId: string, version: string, build: string): string {
  return (
    `// GENERATED by scripts/native-config.ts from capacitor.config.ts and package.json – do not edit.\n` +
    `BLASTYARD_APP_ID = ${appId}\n` +
    `BLASTYARD_VERSION = ${version}\n` +
    `BLASTYARD_BUILD = ${build}\n`
  );
}
