// Native configuration generated from the single source of truth, capacitor.config.ts (T7.1):
// the bundle id goes to the iOS build settings (ios/app-id.xcconfig, included by the debug /
// release xcconfigs → PRODUCT_BUNDLE_IDENTIFIER). Android reads it from the config that
// `npx cap sync` copies into the app assets. Runs automatically after every `npx cap sync`
// (package.json `capacitor:sync:after`).
//   node scripts/run-ts.mjs scripts/native-config.ts

import { writeFileSync } from 'node:fs';
import config from '../capacitor.config';

export function main(): number {
  const appId = config.appId;
  if (!appId || !/^[a-z][a-z0-9]*(\.[a-z][a-z0-9]*)+$/.test(appId)) {
    console.error(`native-config: invalid appId "${appId}" in capacitor.config.ts`);
    return 1;
  }
  writeFileSync(
    'ios/app-id.xcconfig',
    `// GENERATED by scripts/native-config.ts from capacitor.config.ts – do not edit.\n` +
      `BLASTYARD_APP_ID = ${appId}\n`,
  );
  console.log(`native-config: bundle id ${appId} → ios/app-id.xcconfig`);
  return 0;
}
