import { existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import { describe, expect, it } from 'vitest';
import {
  ANDROID_DENSITIES,
  ANDROID_SPLASH,
  IOS_SPLASH,
  iconSvg,
  splashSvg,
} from '../../scripts/brand';

/**
 * T7.2: every icon and launch image the native shells need exists, at its size, generated by
 * `npm run assets` from the code-drawn brand art (scripts/brand.ts).
 */
const ROOT = join(import.meta.dirname, '../..');
const RES = join(ROOT, 'android/app/src/main/res');
const XCASSETS = join(ROOT, 'ios/App/App/Assets.xcassets');

function pngSize(path: string): { w: number; h: number; alpha: boolean } {
  const b = readFileSync(path);
  expect(b.subarray(1, 4).toString('ascii')).toBe('PNG');
  const colorType = b[25] as number;
  return {
    w: b.readUInt32BE(16),
    h: b.readUInt32BE(20),
    alpha: colorType === 4 || colorType === 6,
  };
}

describe('app icons and launch images', () => {
  it('Android: launcher icons, adaptive layers and splash drawables per density', () => {
    for (const d of ANDROID_DENSITIES) {
      expect(pngSize(join(RES, `mipmap-${d.dpi}/ic_launcher.png`))).toMatchObject({
        w: d.icon,
        h: d.icon,
      });
      expect(pngSize(join(RES, `mipmap-${d.dpi}/ic_launcher_round.png`))).toMatchObject({
        w: d.icon,
        h: d.icon,
      });
      expect(pngSize(join(RES, `mipmap-${d.dpi}/ic_launcher_foreground.png`))).toMatchObject({
        w: d.layer,
        h: d.layer,
      });
    }
    for (const s of ANDROID_SPLASH) {
      expect(pngSize(join(RES, `drawable-land-${s.dpi}/splash.png`))).toMatchObject({
        w: s.w,
        h: s.h,
      });
      expect(pngSize(join(RES, `drawable-port-${s.dpi}/splash.png`))).toMatchObject({
        w: s.h,
        h: s.w,
      });
    }
    expect(existsSync(join(RES, 'drawable/splash.png'))).toBe(true);
    expect(readFileSync(join(RES, 'values/ic_launcher_background.xml'), 'utf8')).toMatch(
      /#[0-9a-f]{6}/i,
    );
  });

  it('iOS: a 1024 px icon without transparency and the 2732 px splash set', () => {
    const icon = pngSize(join(XCASSETS, 'AppIcon.appiconset/AppIcon-512@2x.png'));
    expect(icon).toEqual({ w: 1024, h: 1024, alpha: false });
    const contents = JSON.parse(
      readFileSync(join(XCASSETS, 'Splash.imageset/Contents.json'), 'utf8'),
    );
    const names = contents.images.map((i: { filename: string }) => i.filename).sort();
    expect(names).toEqual([...IOS_SPLASH].sort());
    for (const name of IOS_SPLASH) {
      expect(pngSize(join(XCASSETS, 'Splash.imageset', name))).toMatchObject({ w: 2732, h: 2732 });
    }
  });

  it('web: favicon and home-screen icon', () => {
    expect(pngSize(join(ROOT, 'public/favicon.png'))).toMatchObject({ w: 64, h: 64 });
    expect(pngSize(join(ROOT, 'public/apple-touch-icon.png'))).toMatchObject({ w: 180, h: 180 });
  });

  it('the art is plain SVG drawn in code (no external images)', () => {
    for (const svg of [iconSvg(512, 'square'), iconSvg(108, 'foreground'), splashSvg(800, 480)]) {
      expect(svg.startsWith('<svg')).toBe(true);
      expect(svg).not.toMatch(/<image|href="http|url\(http/);
    }
  });
});
